const teamMembers: string[] = [
  "/assets/team/image1.png",
  "/assets/team/image2.png",
  "/assets/team/image3.png",
  "/assets/team/image4.png",
  "/assets/team/image5.png",
  "/assets/team/image6.png",
  "/assets/team/image7.png",
  "/assets/team/image8.png",
  "/assets/team/image9.png",
  "/assets/team/image10.png",
  "/assets/team/image12.png",
  "/assets/team/image13.png",
  "/assets/team/image14.png",
  "/assets/team/image15.png",
  "/assets/team/image16.png",
  "/assets/team/image17.png",
  "/assets/team/image18.png",
  "/assets/team/image19.png",
  "/assets/team/image20.png",
  "/assets/team/image21.png",
  "/assets/team/image22.png",
  "/assets/team/image23.png",
  "/assets/team/image24.png",
  "/assets/team/image25.png",
  "/assets/team/image26.png",
  "/assets/team/image28.png",
  "/assets/team/image29.png",
];

export default teamMembers;
